# Q1

In [2]:
import numpy as np

In [ ]:
arr1=np.arange(1,11)

In [ ]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Q2

In [ ]:
arr2=np.zeros((2,3))

In [ ]:
arr2

array([[0., 0., 0.],
       [0., 0., 0.]])

# Q3

In [ ]:
arr3=np.arange(2,21,2)

In [ ]:
arr3

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

# Q4

In [ ]:
arr1 = np.array([1, 2, 3])

In [ ]:
arr2 = np.array([4,
5, 6])

In [ ]:
arr1+arr2

array([5, 7, 9])

In [ ]:
arr1-arr2

array([-3, -3, -3])

In [ ]:
arr1*arr2

array([ 4, 10, 18])

In [ ]:
arr1/arr2

array([0.25, 0.4 , 0.5 ])

# Q5

In [24]:
arr1=np.random.randint(1,101,100)

In [25]:
arr1

array([100,  76,  23,  31,  57,  28,  26,  85,  20,  81,  87,  86,  27,
        99,  68,   5,  20,  63,  49,  16,  23,  64,   8,  57,  75,  13,
        45,  75,  93,  50,  10,  84,  10,  92,  47,  56,  81,  38,  82,
        25,  88,  47,  47,  11,  54,  34,  24,  21,   3,  59,  93,  28,
        59,  45,  74,  55,  18,  82,  68,  24,  17,  70,  42,  30,  26,
        10,   9,  57,  43,  13,  90,  59,  96,  28,  32,  53, 100,  36,
        70,  28,  54,  38,   7,  87,  30,  11,  33,  36,  71,  35,  13,
        74,   8,  84,  89,  36,   5,  39,   4,  62])

In [26]:
mean = arr1.mean()
mean

47.34

In [27]:
arr1.sort()

In [28]:
arr1

array([  3,   4,   5,   5,   7,   8,   8,   9,  10,  10,  10,  11,  11,
        13,  13,  13,  16,  17,  18,  20,  20,  21,  23,  23,  24,  24,
        25,  26,  26,  27,  28,  28,  28,  28,  30,  30,  31,  32,  33,
        34,  35,  36,  36,  36,  38,  38,  39,  42,  43,  45,  45,  47,
        47,  47,  49,  50,  53,  54,  54,  55,  56,  57,  57,  57,  59,
        59,  59,  62,  63,  64,  68,  68,  70,  70,  71,  74,  74,  75,
        75,  76,  81,  81,  82,  82,  84,  84,  85,  86,  87,  87,  88,
        89,  90,  92,  93,  93,  96,  99, 100, 100])

In [30]:
median=(arr1[49]+arr1[50])/2
median

45.0

In [31]:
std_dev=arr1.std()
std_dev

28.307673871231454

# Q6

In [ ]:
arr1=np.random.randint(1,101,12)

In [ ]:
arr1

array([99,  9,  7, 45, 89, 67, 30, 87,  3, 15, 67, 93])

In [ ]:
arr1.reshape(3,4)

array([[99,  9,  7, 45],
       [89, 67, 30, 87],
       [ 3, 15, 67, 93]])

# Q7

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
np.square(arr)

array([ 1,  4,  9, 16, 25])

# Q8

In [ ]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Q9


In [ ]:
a= np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [ ]:
a.dot(b)

32

# Q10

In [ ]:
arr1=np.random.randint(1,101,10)

In [ ]:
arr1

array([ 7, 92, 43, 38,  6, 56, 45, 79, 91,  6])

In [ ]:
arr1.argmax()

1

In [ ]:
arr1.argmin()

4

#Q11


In [ ]:
a=np.zeros((4,4))
b=np.ones((4,4))
c=np.concatenate((a,b))
d=np.concatenate((a,b),axis=1)
print('Vertical Concatenation-\n',c)
print('Horizontal Concatenation-\n',d)

Vertical Concatenation-
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Horizontal Concatenation-
 [[0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]]


#Q12

In [ ]:
arr=np.arange(1,17).reshape(4,4)
print(arr)
print('Sum of each column is ',np.sum(arr,axis=0) )
print('Sum of each row is ',np.sum(arr,axis=1) )

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Sum of each column is  [28 32 36 40]
Sum of each row is  [10 26 42 58]


#Q13

In [ ]:
a=np.array([[4,9],[5,8],[1,7]])
b=np.array([[3,9],[5,2],[6,7]])
c=np.intersect1d(a,b)
print("The common elements between a and b are ",c)

The common elements between a and b are  [5 7 9]


#Q14

In [ ]:
x=np.array([1,2,3,-4,-5,-6])
x[x<0]=0
x

array([1, 2, 3, 0, 0, 0])

#Q15

In [ ]:
arr1=np.random.randint(1,101,100)
arr1.sort()
arr1

array([  2,   3,   8,   8,   8,  10,  10,  11,  15,  15,  16,  17,  17,
        18,  18,  19,  20,  21,  21,  27,  28,  28,  29,  29,  30,  31,
        32,  33,  33,  34,  34,  35,  35,  36,  37,  40,  40,  41,  42,
        43,  43,  46,  47,  48,  48,  49,  50,  50,  50,  51,  52,  52,
        53,  53,  55,  55,  58,  58,  59,  60,  61,  61,  62,  63,  64,
        64,  65,  65,  66,  67,  68,  68,  68,  70,  72,  73,  74,  75,
        76,  77,  79,  79,  81,  82,  83,  84,  84,  86,  87,  88,  88,
        93,  93,  95,  97,  97,  98,  98,  99, 100])

#Q16

In [ ]:
a=np.array([1,2,3,4,5])
b=np.array([6,8,10,12,14])
c=np.absolute(a-b)
print("The element-wise absolute difference between the two arrays is ",c)

The element-wise absolute difference between the two arrays is  [5 6 7 8 9]


#Q17

In [22]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
firstrow=arr[0]
lastcol=arr[:,[-1]]
print("First row is\n",firstrow)
print("Last Column is\n",lastcol)


First row is
 [1 2 3]
Last Column is
 [[3]
 [6]
 [9]]


#Q18

In [11]:
a=np.array([1,2,3,4,5])
x=a[0:len(a)+1]
print(x)

[1 2 3 4 5]


#Q19

In [14]:
arr=np.array([[10,1,14,16,18,20],[22,24,26,28,30,32],[34,36,38,40,42,44],[46,48,50,52,54,56],[58,60,62,64,66,68],[70,72,74,76,78,80]])
x=arr[2:4,[2,3]]
print('Original array is\n',arr)
print('Central 2x2 elements include\n',x)

Original array is
 [[10  1 14 16 18 20]
 [22 24 26 28 30 32]
 [34 36 38 40 42 44]
 [46 48 50 52 54 56]
 [58 60 62 64 66 68]
 [70 72 74 76 78 80]]
Central 2x2 elements include
 [[38 40]
 [50 52]]


#Q20

In [21]:
a=np.array([1,2,3,4,5])
x=a[::-1]
x

array([5, 4, 3, 2, 1])